server:
  port: 9001
  use-forward-headers: true
  servlet:
    session:
      timeout: 86400s
      cookie:
        http-only: true
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  session:
    store-type: redis
  # thymeleaf:
    # if you want to deploy html files separately(not in jar files), uncomment below
    # prefix: file:./templates/
    # cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

mybatis:
  mapper-locations:
    - classpath:dao/**/*.xml
    - classpath*:dr/sbs/mbg/mapper/*.xml

logging:
  level:
    org.springframework.web: ERROR
    dr.sbs: DEBUG
  file: ./logs

app:
  # snowflake workerId and dataCenterId, see "hutool IdUtil.createSnowflake(workerId, dataCenterId)"
  workerId: 1
  dataCenterId: 1
