spring:
  devtools:
    restart:
      enabled: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://remote-ip:3306/starter?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456

logging:
  level:
    org.springframework.web: ERROR
    dr.sbs: ERROR
